name: chess3man_engine
version: 0.0.7
description: 3manchess engine library
authors:
- "Michał Krzysztof Feiler <archiet@platinum.edu.pl>"
homepage: "http://github.com/ArchieT/chess3man_engine"
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  charcode: ^1.1.0
  built_collection: ^1.0.4
  test: ^0.12.9
  worker: ^0.5.0
  tuple: ^1.0.1