name: chess3man_engine
version: 0.0.1
description: 3manchess engine library
authors:
- "Michał Krzysztof Feiler <archiet@platinum.edu.pl>"
homepage: "http://github.com/ArchieT/chess3man_engine"
dependencies:
  charcode: any
